[2024-10-16T07:06:12.079+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: db_to_offline_store.explore_and_validate_task scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2024-10-16T07:06:12.209+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: db_to_offline_store.explore_and_validate_task scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2024-10-16T07:06:12.209+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T07:06:12.209+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-10-16T07:06:12.209+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T07:06:12.224+0000] {taskinstance.py:1389} INFO - Executing <Task(DockerOperator): explore_and_validate_task> on 2022-01-01 00:00:00+00:00
[2024-10-16T07:06:12.230+0000] {standard_task_runner.py:52} INFO - Started process 384 to run task
[2024-10-16T07:06:12.233+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'db_to_offline_store', 'explore_and_validate_task', 'scheduled__2022-01-01T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline/db_to_offline_store.py', '--cfg-path', '/tmp/tmpjm3nv_6c', '--error-file', '/tmp/tmp4gku9wrz']
[2024-10-16T07:06:12.234+0000] {standard_task_runner.py:80} INFO - Job 8: Subtask explore_and_validate_task
[2024-10-16T07:06:12.292+0000] {task_command.py:371} INFO - Running <TaskInstance: db_to_offline_store.explore_and_validate_task scheduled__2022-01-01T00:00:00+00:00 [running]> on host bc2dbf4723f9
[2024-10-16T07:06:12.366+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mlopsvn
AIRFLOW_CTX_DAG_ID=db_to_offline_store
AIRFLOW_CTX_TASK_ID=explore_and_validate_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-01T00:00:00+00:00
[2024-10-16T07:06:12.383+0000] {docker.py:262} INFO - Starting docker container from image mlopsvn/mlops_crash_course/data_pipeline:latest
[2024-10-16T07:06:12.385+0000] {docker.py:273} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-10-16T07:06:12.640+0000] {docker.py:324} INFO - 2024-10-16 07:06:12,639 - utils.logger - INFO - Exploring and validating...
[2024-10-16T07:06:12.816+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=db_to_offline_store, task_id=explore_and_validate_task, execution_date=20220101T000000, start_date=20241016T070612, end_date=20241016T070612
[2024-10-16T07:06:12.846+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-10-16T07:06:12.886+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
